/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Day12;

import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ThuyVT
 */
public class DaLuong extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form DaLuong
     */
    public DaLuong() {
        initComponents();
        Thread th = new Thread(this);
        th.start();// chạy đa luồng
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTieuDe = new javax.swing.JLabel();
        lblDHMayTinh = new javax.swing.JLabel();
        lblDHChuongTrinh = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTieuDe.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        lblTieuDe.setForeground(new java.awt.Color(255, 0, 153));
        lblTieuDe.setText("ĐA LUỒNG ");

        lblDHMayTinh.setText("Thời gian trên máy tính");

        lblDHChuongTrinh.setText("Thời gian chạy chương trình");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDHChuongTrinh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(lblDHMayTinh)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(lblTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblTieuDe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDHMayTinh)
                    .addComponent(lblDHChuongTrinh))
                .addContainerGap(228, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DaLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DaLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DaLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DaLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DaLuong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDHChuongTrinh;
    private javax.swing.JLabel lblDHMayTinh;
    private javax.swing.JLabel lblTieuDe;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        int s = 0; // giây
        int m = 0; // phút
        int h = 0; // giờ
        // đồng hồ máy tính
        int giay = 0; // giây
        int phut = 0; // phút
        int gio = 0; // giờ
        
        while (true) {
            s += 1;
            if (s == 60) {
                m += 1;
                s = 0;
            }
            if (m == 60) {
                h += 1;
                m = 0;
                s = 0;
            }
            if (h == 24) {
                h = 0;
                m = 0;
                s = 0;
            }
            lblDHChuongTrinh.setText(h+":" + m + ":" + s);
            // Lấy thông tin của giờ, phút giây của hệ thống
            Calendar cal = Calendar.getInstance();
            gio = cal.get(Calendar.HOUR);// giờ hiện tại
            phut = cal.get(Calendar.MINUTE);// phút
            giay = cal.get(Calendar.SECOND);// giây
            lblDHMayTinh.setText(gio + ":" + phut + ":" + giay);
            
            String chuDau = lblTieuDe.getText().substring(0, 1);
            String sauCat = lblTieuDe.getText().substring(1); // loại bỏ chữ đầu tiên
            lblTieuDe.setText(sauCat + chuDau);
            
            try {
                // ngắt giữa các vòng lặp 1s
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                Logger.getLogger(DongHo.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
}
